site_name: InfoTIC's
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        primary: teal
        accent: lime
nav:
  - Intro: "index.md"
  - Documentation:
      - Requirements: "req.md"
      - Design: "dsg.md"
      - Implementation: "imp.md"
      - Testing: "test.md"
  - Services:
      - Broker: "broker.md"
      - Sensor: "sensor.md"
      - Server: "server.md"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: '&copy; 2023 <a href="https://github.com/Alejolivo" target="_blank" rel="noopener">Alejo Olivo</a> | <a href="https://github.com/federodriguez16" target="_blank" rel="noopener">Federico Rodriguez</a>'
